ltcl-mentor/LTCL_Helper

public/css/Search/search.css
public/css/Search/show.css
public/js/app.js
resources/js/components/Search/topicForm.js
resources/views/Search/search.blade.php
resources/views/Search/show.blade.php
resources/views/layouts/app.blade.php

デザイン変更(生徒用ページのみ)

---

public/css/Mentor/show.css
public/css/Search/search.css
public/css/Search/show.css
public/js/app.js
resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Mentor/Question/Show/preview.js
resources/views/Question/show.blade.php
resources/views/Search/show.blade.php

・公開用ページ
質問詳細→吹き出し修正
・管理用ページ
管理画面→質問プレビュー修正

デザイン修正 2021/07/05

---

public/css/Mentor/mentor.css
public/css/Mentor/show.css
public/css/Search/show.css
public/css/app.css
public/js/app.js
resources/views/Document/show.blade.php
resources/views/layouts/app.blade.php

修正箇所
・メンター用関連記事詳細画面
→一部クラス名変更
・メンター用プレビュー画面

デザイン修正 2021/7/12 メンター用ページ

---

package-lock.json
package.json
public/css/Search/demo.css
public/js/app.js
resources/js/components/demo.js

・SP版追加
・文字サイズ、色、ブロックの余白修正
・関連記事部分修正残りあり

公開部分の質問詳細画面デモ版デザイン修正

---

resources/js/components/Public/Search/Freeword/form.js

問題の修正を行いました。
問題がなさそうであればmergeをお願いいたします。

検索フォームでEnterを押すとリロードする問題の修正

---

app/Question.php

お疲れ様です。
大文字、小文字を区別してしまう問題の解消をしました。
コード確認後、問題がなければmergeをお願いします。

検索フォームにて大文字と小文字を区別する問題の解消

---

app/Question.php

検索ができない問題の修正

---

app/Comment.php
app/Http/Controllers/CommentController.php
resources/js/components/Alert.js
resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Public/Question/Show/comments/comment.js
resources/js/components/Public/Question/Show/comments/comments.js
resources/js/components/Public/Question/Show/comments/create.js
resources/js/components/Public/Question/Show/comments/edit.js

コメント投稿に関するフラッシュメッセージ表示

---

resources/js/components/Public/Search/Freeword/Result/questions.js

お疲れ様です。
paginationが正常に動作しない問題を修正しました。
問題がなければmergeをお願い致します。

paginationの修正

---

app/College.php
app/Console/Commands/EventCommand.php
app/Event.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/ReactController.php
app/Info.php
database/migrations/2022_03_29_203646_add_column_to_infos_table.php
database/migrations/2022_03_30_165319_create_events_table.php
public/css/Search/show.css
public/css/destyle.css
resources/js/components/Alert.js
resources/js/components/Breadcrumbs.js
resources/js/components/Mentor/Event/Create/Create.js
resources/js/components/Mentor/Event/Index/Index.js
resources/js/components/Mentor/Top.js
resources/js/components/Public/Home/Home.js
resources/js/components/Public/Home/information/create.js
resources/js/components/Public/Home/information/information.js
resources/js/components/Public/Home/information/infos.js
resources/js/components/Public/Home/information/selectEvents.js
resources/js/components/Public/Home/information/selectTarget.js
resources/js/components/Public/Question/Show/documents.js
resources/js/components/Route.js
routes/web.php

・お知らせの詳細表示
・お知らせのslack通知
・イベント登録機能 → お知らせからslackへのテンプレを選べる

お知らせ追加機能修正/イベント追加機能実装

---

resources/js/components/Public/Contact/Contact.js
resources/js/components/Public/Question/Create/Create/Create.js
resources/js/components/Public/Question/Create/Create/question-form/original-text-form/originalTextForm.js
resources/js/components/Public/Question/Create/Create/question-form/questionForm.js
resources/js/components/Public/Search/Condition/Search/Forms/additionalForms/curriculum-number/curriculum-number.js
resources/js/components/Public/Search/Condition/Search/Forms/additionalForms/curriculum-number/select.js

バリデーションの修正

---

resources/js/components/Mentor/Event/Create/Create.js
resources/js/components/Public/Contact/Contact.js
resources/js/components/Public/Home/information/create.js
resources/js/components/Public/Home/information/selectTarget.js
resources/js/components/Public/Question/Create/Create/Create.js
resources/js/components/Public/Question/Create/Create/question-form/original-text-form/originalTextForm.js
resources/js/components/Public/Question/Create/Create/question-form/questionForm.js
resources/js/components/Public/Search/Condition/Search/Forms/additionalForms/curriculum-number/curriculum-number.js
resources/js/components/Public/Search/Condition/Search/Forms/additionalForms/curriculum-number/select.js

バリデーションの修正を行いました。
問題がなければmergeをお願いします。

バリデーション関連の修正

---

resources/js/components/Public/Question/Create/Create/Create.js
resources/js/components/Public/Question/Create/Create/default-form.js
resources/js/components/Public/Question/Create/Create/question-form/original-text-form/originalTextForm.js
resources/js/components/Public/Question/Create/Create/question-form/original-text-form/picture.js
resources/js/components/Public/Question/Create/Create/question-form/questionForm.js

質問投稿ページのデザインを修正したので確認よろしくお願いします。
まだ、ボタン押下時の機能などは調整していません。

質問投稿ページのデザイン修正

---

public/css/Public/top.css
resources/js/components/Breadcrumbs.js
resources/js/components/Public/Question/Create/Create/default-form.js
resources/js/components/Public/User/MyPage.js

マイページデザイン編集

---

app/Question.php
resources/js/components/Public/Question/Index/Index/article.js
resources/js/components/Public/User/MyPage.js

マイページへペジネーションの追加

---

resources/js/components/Public/Question/Index/Index/article.js

質問一覧のデザインの修正

---

public/css/Search/show.css
resources/js/components/Mentor/Question/Show/Publish/preview.js
resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Public/Question/Show/Show.js
resources/js/components/Public/Question/Show/comments/comment.js
resources/js/components/Public/Question/Show/comments/comments.js
resources/js/components/Public/Question/Show/comments/create.js
resources/js/components/Public/Question/Show/documents.js
resources/js/components/Public/Question/Show/question.js
resources/js/components/Public/Question/Show/related-questions.js
resources/js/components/Public/User/QuestionShow.js

マイページから閲覧する際の、個別質問ページのデザインを修正しました。
他のページから見る際の、個別質問ページも引き続き修正していきます。
よろしくお願いします。

個別質問ページ（マイページ）のデザイン修正

---

app/Http/Controllers/HomeController.php
public/css/Public/history.css
resources/js/components/Public/History/History.js

質問閲覧機能の修正及び、デザインの修正

---

resources/js/components/Public/Question/Create/Create/question-form/original-text-form/originalTextForm.js
resources/js/components/Public/Question/Show/Show.js
resources/js/components/Public/Question/Show/comments/comment.js
resources/js/components/Public/Question/Show/comments/comments.js
resources/js/components/Public/Question/Show/comments/create.js
resources/js/components/Public/User/QuestionShow.js

デザインの崩れていたところや、修正の必要な箇所を直しました。
よろしくお願いします。

細かいデザインの修正

---

resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Mentor/Question/Show/question.js
resources/js/components/Public/Question/Create/Create/default-form.js
resources/js/components/Public/Question/Show/question.js

バリデーション機能の修正

---

app/Http/Controllers/HomeController.php
public/css/Public/history.css
resources/js/components/Public/History/History.js

質問閲覧履歴のデザイン修正

---

.env.example
app/College.php
app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/QuestionController.php
app/Http/Controllers/ReactController.php
app/Http/Controllers/UserController.php
app/Info.php
public/css/Public/top.css
resources/js/components/Alert.js
resources/js/components/Public/Home/Home.js
resources/js/components/Public/Home/Manage/manage.js
resources/js/components/Public/Home/Manage/userIndex.js
resources/js/components/Public/Home/Q&A/qa.js
resources/js/components/Public/Home/Top/calendar/info.js
resources/js/components/Public/Home/Top/information/create.js
resources/js/components/Public/Home/Top/information/information.js
resources/js/components/Public/Home/Top/information/infos.js
resources/js/components/Public/Home/Top/information/selectEvents.js
resources/js/components/Public/Home/Top/information/selectTarget.js
resources/js/components/Public/Home/Top/top.js
resources/js/components/Public/Home/modal.js
resources/js/components/Public/Home/modal/addEvent.js
resources/js/components/Public/Home/modal/deleteInfo.js
resources/js/components/Public/Home/modal/showEvent.js
resources/js/components/Public/Home/modal/showInfo.js
resources/js/components/Public/Home/modal/studentForm.js
resources/js/components/Public/Home/modal/userRegister.js
resources/js/components/Public/Home/tabpanel.js
routes/web.php

・管理用ページ作成
・他ページのメンター用アカウントとの識別
・各種モーダル作成

トップ画面メンター用デザイン修正

---

resources/js/components/Layout/user-icon.js
resources/js/components/Public/Question/Index/Index/questions.js
resources/js/components/Public/User/AdminMypage.js
resources/js/components/Public/User/MyPage.js
resources/js/components/Public/User/Mypage/basicInformation.js
resources/js/components/Route.js

管理者用マイページを作成しました。
ご確認をお願いいたします。

管理者用マイページの作成

---

resources/js/components/Public/User/AdminMypage.js

管理者用のマイページの修正

---

database/migrations/2022_04_13_114856_add_status_column_to_questions_table.php
database/seeds/QuestionTableSeeder.php

カラム追加用のマイグレーションファイルと、questionsテーブル用のseederを修正しました。
質問のステータスはintegerで管理する予定です。
- status => 0 -> 未対応
- status => 1 -> 対応中
- status => 2 -> 解決済み
- status => 3 -> 要対応

questionsテーブrに質問ステータスカラムを追加

---

resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Mentor/Question/Show/question.js

[update]ステータス変更用セレクトボックスの位置を変更

---

resources/js/components/Public/Question/Show/Show.js
resources/js/components/Public/User/QuestionShow.js

Publicでは質問一覧に遷移するようにして、マイページからの質問ページではマイページに戻るように設定しました。

[update]質問一覧に戻るボタンを押した際の遷移先を変更

---

app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/ReactController.php
app/Question.php
resources/js/components/Public/Home/Manage/manage.js
resources/js/components/Public/Home/modal/studentForm.js
resources/js/components/Public/Home/modal/userRegister.js
resources/js/components/Public/Home/tabpanel.js
resources/js/components/Public/Question/Index/Index/Index.js
resources/js/components/Public/Question/Index/Index/questions.js
resources/js/components/Public/User/AdminMypage.js

お疲れ様です。
新規ユーザー登録じに発生するバグの修正と、質問一覧でステータスが見えるようにし、ステータスでカテゴリ分けできるようにしました。
ご確認をお願いします。

管理者ページのペジネーションの修正及び、質問一覧へのステータスの実装

---

resources/js/components/Breadcrumbs.js
resources/js/components/Public/Question/Create/Create/selectForm.js
resources/js/components/Public/Question/Create/Create/topicForm.js
resources/js/components/Public/Question/Show/Show.js

パンくずリストと個別質問ページの一覧へ戻るボタンの微修正

---

app/Question.php
resources/js/components/Breadcrumbs.js
resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Public/History/History.js
resources/js/components/Public/Question/Index/Index/questions.js
resources/js/components/Public/Question/Show/Show.js
resources/js/components/Public/User/AdminMypage.js

パンくずリストの修正、質問閲覧記録機能の修正などを行いました。
また、`Question.php`の34行目で多対多のリレーションに`belongsTo`を使っていたので、`belongsToMany`に修正してあります。

ぱんくずリストの修正など

---

resources/js/components/Mentor/Question/Show/Show.js

[update]パンくずリストの修正

---

app/Http/Controllers/ReactController.php
app/Question.php
resources/js/components/Mentor/Question/Index/questionsForMentor.js
resources/js/components/Public/Home/Q&A/qa.js
resources/js/components/Route.js
routes/web.php

メンター用質問一覧ページの作成

---

resources/js/components/Breadcrumbs.js
resources/js/components/Public/Home/Q&A/questionsForMentor.js
resources/js/components/Public/Question/Index/Index/Index.js
resources/js/components/Public/Question/Index/Index/article.js
resources/js/components/Public/Question/Index/Index/questions.js
resources/js/components/Public/User/AdminMypage.js
resources/js/components/Route.js

要対応質問リストのデザイン修正、及びサクッと直せそうな範囲でwarningとvarなどの削除を行いました。
ご確認をお願いします。

デザインの微調整、及びリファクタリング

---

resources/js/components/BreakingPoint.js

ブレーキングポイントをファイル内で定義して、一括管理できるようにしました。

[add]ブレーキングポイントをファイルで一括管理

---

package-lock.json
package.json
resources/js/components/BreakingPoint.js
resources/js/components/Public/Question/Index/Index/Index.js
resources/js/components/Public/Question/Index/Index/article.js
resources/js/components/Public/Question/Index/Index/questions.js

質問一覧ページのレスポンシブデザイン対応

---

resources/js/components/Public/Home/Top/information/create.js
resources/js/components/Public/Home/Top/information/information.js
resources/js/components/Public/Home/modal/showInfo.js

[update]モーダルで改行を保持するように修正

---

resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Mentor/Question/Show/question.js

[update]メンター用質問個別ページのレスポンシブデザインを修正

---

resources/js/components/Mentor/Question/Show/Publish/publish.js
resources/js/components/Mentor/Question/Show/Publish/responsive/publishContentMobile.js
resources/js/components/Mentor/Question/Show/Publish/responsive/publishContentPc.js
resources/js/components/Mentor/Question/Show/Show.js
resources/js/components/Mentor/Question/Show/responsive/showContentMobile.js
resources/js/components/Mentor/Question/Show/responsive/showContentPc.js

レスポンシブの際に、コンポーネント毎入れ替えるようにしました。
よろしくお願いします。

レスポンシブ機能の修正
